import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare let self: ServiceWorkerGlobalScope;

// Cleanup old caches and claim clients immediately
cleanupOutdatedCaches();
clientsClaim();

// Precache static assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// --- Manifest-Driven Asset Caching Logic ---
const ASSET_CACHE_NAME = 'event-assets-cache-v1';

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'CACHE_EVENT_ASSETS') {
        const { urls } = event.data.payload;

        event.waitUntil(
            caches.open(ASSET_CACHE_NAME).then((cache) => {
                console.log(`[SW] Pre-caching ${urls.length} event assets...`);
                return cache.addAll(urls);
            })
        );
    }
});

// Self-skip waiting
self.addEventListener('install', () => {
    self.skipWaiting();
});
